### ISSUE TITLE
Hospedagem no GHPages e CNAME

### ISSUE THREAD

**Issue by gjuniioor** [devnaestrada/devnaestrada.com.br#13]
Opa! O site é com o Jekyll, então poderia utilizar o próprio Github Pages para hospedá-lo, já pensaram nisso? Pode economizar uma grana com hospedagem e fica mais rápido e menos trabalhoso de modificações irem pro ar.

Basicamente, só criar um arquivo `CNAME` com o conteúdo `devnaestrada.com.br` e criar uma entrada `CNAME` direcionando para `devnaestrada.github.io`.

> Ah! Como o repositório está com outro nome, seria bom renomear para `devnaestrada.github.io`, ou utilizar um branch `gh-pages` para ter a página na web pelo gh-pages.

**Comment by femontanha** [comment]
Fala @gjuniioor obrigado pela sugestão! Nossos planos por enquanto são outros por isso estamos hospedados em um outro host! Obrigado!

**Comment by gjuniioor** [comment]
Ah, tranquilo @femontanha . Estamos ai :D
