### ISSUE TITLE
Melhorar SEO

### ISSUE THREAD

**Issue by luisfmsouza** [devnaestrada/devnaestrada.com.br#14]
O DevNaEstrada não aparece na primeira página em buscas no Google como:

Busca | página
---------|----------
podcast fronted | 2ª página
podcast desenvolvimento | 2ª página
podcast tecnologia | não achei nas 5 primeiras
podcast | não achei nas 20 primeiras

Além dessas buscas, seria interessante pro DevNaEstrada aparecer quando alguém buscar por `Zofe` ou `Grok`.

Melhorias:
- [x] Adicionar meta description
- [x] Adicionar uma descrição no titulo da home: DevNaEstrada | Podcast do desenvolvedor 
- [x] Adicionar uma descrição no titulo dos episódios: DNE #51 [titulo] | Podcast do desenvolvedor 

Além disso, seria bacana usar o https://www.google.com/webmasters/tools/home?hl=pt-BR pra identificar melhorias. Imagino que isso seja tarefa pra vocês @femontanha e @raymonsanches.

**Comment by femontanha** [comment]
Sobre o google webmaster @luisfmsouza  já estamos lá, melhorias agressivas não tem, tem algumas bem especificas mas pode deixar comigo

**Comment by guiluchesi** [comment]
Se queremos melhorar a posição quanto a buscas por podcast desenvolvimento, não seria melhor colocar os títulos citados como "[...] | Podcast de desenvolvimento"?

**Comment by femontanha** [comment]
Já temos um G+ https://plus.google.com/+DevnaestradaBrazil/

**Comment by guiluchesi** [comment]
@femontanha rel publisher adicionado com sucesso ;)

**Comment by luisfmsouza** [comment]
@femontanha o H1 tem um pesoa razoável no SEO, não seria melhor deixar a frase "Desenvolvimento..." nele?

**Ao invés de:**
```
<h1>Episódio novo toda Sexta-feira</h1>
<h2>Desenvolvimento Front-end & Back-end</h2>
```

**Não seria melhor inverter para:**
```
<h1>Desenvolvimento Front-end & Back-end</h1>
<h2>Episódio novo toda Sexta-feira</h2>
```

Uma outra ideia é incrementar ele com "Podcast sobre...", o que vc acha?
```
<h1>Podcast sobre desenvolvimento Front-end & Back-end</h1>
```

**Comment by lnfnunes** [comment]
@luisfmsouza +1

**Comment by guiluchesi** [comment]
@luisfmsouza +2

**Comment by femontanha** [comment]
@luisfmsouza Acho bacana cara! Manda bala

**Comment by femontanha** [comment]
@luisfmsouza @guiluchesi @lnfnunes As alterações que fizemos, principalmente de title e description foram atualizadas no google.

Procurei por "Podcast Desenvolvimento" e aparecemos na segunda página do google.
Ainda não é o melhor, mas já melhorou bastante, o que acham?

![screen shot 2016-02-29 at 06 24 23](https://cloud.githubusercontent.com/assets/722757/13390448/1e79659e-dead-11e5-97a7-eea23946df13.png)

**Comment by luisfmsouza** [comment]
Show!

Aqui apareceu na primeira página(último resultado) pras buscas:

- Podcast desenvolvimento
- Podcast frontend
- Podcast backend

Agora é a hora do google bomb?

**Comment by gabrielmelo** [comment]
Uma boa prática seria solicitar aos convidados que referenciem o DevNaEstrada. 

Acredito que cada convidado(quando possível) poderia criar um post no medium ou blog pessoal divulgando o episódio gravado e, dessa forma, fortalece o domínio. Ou seja, Link Building.

**Comment by gabrielmelo** [comment]
Algo que pode ser feito pensando em SEO é criar um título na seção dos podcasts. O print de Outline da marcação html.
Melhoria a semântica deste conteúdo. Atualmente, os artigos não estão dentro de um contexto definido ou um section definida com titulo.  

![screenshot](https://cloud.githubusercontent.com/assets/4544108/13645885/cef728ec-e60b-11e5-991b-8a8ea196157b.png)

Obs.: O título é apenas exemplo.

**Comment by gabrielmelo** [comment]
Um dica: Melhoria para estrutura da marcação.
- Remover os títulos para dentro de cada lista. Assim, terá mais sentindo para o contexto e penso que pode melhorar na indexação. 
- Tornar esse bloco como section e a class container seria realocada para dentro do bloco. Dessa forma, a estrutura da marcação mudaria, se tornaria irmão do título principal(hero) e não mais filha. Segue o print. 

Se de acordo, posso fazer essa alteração. 

![screenshot](https://cloud.githubusercontent.com/assets/4544108/13651210/1d1c5bb4-e625-11e5-8d96-f56b839a44bb.png)

**Comment by luisfmsouza** [comment]
Qual o nome desse plugin do Chrome @gabrielmelo ?

**Comment by gabrielmelo** [comment]
@luisfmsouza é o HTML5 Outliner. O resultado demonstrado é o Outliner do html, meio que um sumário. 
 
Nesse caso que apontei, melhoraria a estrutura do html e semântica de html.

**Comment by femontanha** [comment]
Fala @gabrielmelo, pode abrir um PR que agente confere tudo :+1: 
Obrigado!

**Comment by femontanha** [comment]
@luisfmsouza @guiluchesi @lnfnunes @gabrielmelo @raymonsanches pessoal, obrigado a todos pelas dicas e Pull Requests aqui, já implementamos a maioria das coisas! Se tiverem mais algo a acrescentar peço que abram uma nova Issue ou PR! Vou fechar essa issue aqui!
