### ISSUE TITLE
Imagem off

### ISSUE THREAD

**Issue by augustoar** [devnaestrada/devnaestrada.com.br#148]
Trocar link da imagem, o atual está off no twitter, segue o link:
```
https://pbs.twimg.com/profile_images/960677676884418560/wS6CtNj3.jpg
```

https://github.com/devnaestrada/devnaestrada.com.br/blob/75d25111ae3438926168bf9dbe06c0da9430bbd8/_scss/modules/structure/_footer.scss#L29

**Comment by femontanha** [comment]
Valeu @gregoryfm !

**Comment by femontanha** [comment]
<img width="725" alt="screen shot 2018-02-15 at 15 48 55" src="https://user-images.githubusercontent.com/722757/36272119-c2e2169a-1267-11e8-88a2-7bef340aa2f5.png">

just to show the result :)
