### ISSUE TITLE
Botão de compartilhar não funciona

### ISSUE THREAD

**Issue by ftonato** [devnaestrada/devnaestrada.com.br#24]
Hoje estava ouvindo o [último episódio ~ DNE 43 - Brasileiro em Angola](http://devnaestrada.com.br/2016/03/04/devnaestrada-brasileiro-angola.html) e quando fui compartilhar, abriu a [página para fazer o _tweet_](https://twitter.com/intent/tweet), mas sem conteúdo.

Eu acessei no mínimo uns 4 episódios e todos estão estavam com esse problema. Os episódios que eu acessei foram os (43, 42, 40, 38).

Segue a parte de código que está gerando esse "problema" nas **postagem** [_layouts/post.htm](https://github.com/devnaestrada/devnaestrada.com.br/blob/master/_layouts/post.html#L44)

Uma sugestão é adicionar o `título` e a `url` do episódio, seguido de `via @devnaestrada`.
Segue um exemplo **prático**:
```html
<a class="twitter-share-button" href="https://twitter.com/intent/tweet?text={{ page.title }}&url={{ site.url }}{{ page.url }}&via={{ site.twitter_user }}" rel="nofollow" target="_blank" title="Compartilhe no Twitter">Tweet</a>
```
Resutado com o episódio 43:
```
DNE 43 - Brasileiro em Angola | Podcast sobre desenvolvimento front-end & back-end http://devnaestrada.com.br/2016/03/04/devnaestrada-brasileiro-angola.html via @devnaestrada
```

Espero ter ajudado :)

/cc @raymonsanches @femontanha

**Comment by femontanha** [comment]
Fala @ftonato, dei uma debugada aqui e eu segui toda a recomendação da tool button do twitter.
Testei aqui e está tudo certo. Provavelmente pode ter sido uma "Instabilidade" no código deles nesse dia. Não tem muito o que fazer sendo um código de terceiro que apenas ajuda.

Você consegue ver se está ok hoje? Senão me de mais detalhes de browser, SO e etc.
Obrigado.

**Comment by ftonato** [comment]
E aí @femontanha, bastante estranho, mas parece que está funcionando agora ^^
Bom, agora que você falou sobre a "Instabilidade", de fato poderia ser isso mesmo, visto que o botão não aparecia, o que aparecia era apenas o texto _Tweet_.

Dessa forma, creio que tudo já está resolvido :smile:

**Comment by ftonato** [comment]
Beleza @femontanha?

Só para constar, quando fiz o teste que percebi que não estava funcionando, eu estava usando um Win 8 e Firefox 44.0.2.
Já ontem quando eu fiz a última postagem, eu usava um Ubuntu 15:10 e Firefox 42.0.2 (se não em engano).
Todavia acabei de acessar do mesmo computador que reportei o problema, e o erro permanece...
Como haviamos comentado, pode ser a "Instabilidade", mas permanece acontecendo...

Acessei a página do [episódio 43](http://devnaestrada.com.br/2016/03/04/devnaestrada-brasileiro-angola.html) e o resultado foi esse:

![problema](https://cloud.githubusercontent.com/assets/5417662/13567883/b92ae70e-e43c-11e5-80cf-9bf4bdc83f02.png)
