### ISSUE TITLE
Wrong URL when sharing a post on Twitter

### ISSUE THREAD

**Issue by lucascaton** [devnaestrada/devnaestrada.com.br#26]
I was clicking on this button:

![image](https://cloud.githubusercontent.com/assets/86755/13726383/ca110778-e910-11e5-9ad8-2ab00161f912.png)

then realised the URL displayed was with a double `/`:

<img width="581" alt="screen_shot_2016-03-13_at_11_44_16_am" src="https://cloud.githubusercontent.com/assets/86755/13726388/044e2326-e911-11e5-8d14-98ceb4310f31.png">

I tried to fix it, but I couldn't find where was that in the codebase.

**Comment by ptcmariano** [comment]
i tried and not find it. this is layout > https://github.com/devnaestrada/devnaestrada.com.br/blob/master/_layouts/post.html

**Comment by cynthiapereira** [comment]
The problem are in Canonical URL:

https://github.com/devnaestrada/devnaestrada.com.br/blob/master/_includes/structure/head.html#L27

Remove that code to fix double slash:

```
prepend: site.baseurl |
```
