### ISSUE TITLE
Inserir Search no site.

### ISSUE THREAD

**Issue by igordcsouza** [devnaestrada/devnaestrada.com.br#29]
[FAZENDO] 
Vou inserir uma busca básica no site, como foi comentado no ultimo epi. Quem puder depois dar um tapa no layout seria muito bom.

**Comment by gabrielmelo** [comment]
@igordcsouza Eu posso olhar o layout da busca. Quando finalizar o código avisa.

**Comment by igordcsouza** [comment]
@gabrielmelo da uma olhada no meu github. Ta no branch search. ;)

**Comment by igordcsouza** [comment]
Talvez ainda faça umas modificações mais a noite, mas nada pesado.

**Comment by gabrielmelo** [comment]
@igordcsouza desculpas a demora. Amanhã vou conferir.

**Comment by igordcsouza** [comment]
Nada :) 
Faz tranquilo, quando tu tiver tempo! 

Att,
Igor Souza

**Comment by emersonmellado** [comment]
Legal isso Igor. Precisa de ajuda?

**Comment by igordcsouza** [comment]
@emersonmellado então, eu não atualizei nada desde esse dia ai. Se der pra arrumar ele no layout da pagina seria bacana. Tu tem como fazer? :)

**Comment by emersonmellado** [comment]
Opa, dá sim. tá aqui né? https://github.com/igordcsouza/devnaestrada.com.br/tree/search

**Comment by igordcsouza** [comment]
Isso, acabei de dar merge com o master. Fica a vontade.

**Comment by femontanha** [comment]
@igordcsouza Obrigado pelo PR! Vou trabalhar nisso agora!

**Comment by igordcsouza** [comment]
por nada! 👍

**Comment by femontanha** [comment]
Done here: https://github.com/devnaestrada/devnaestrada.com.br/pull/34
