### ISSUE TITLE
Standardize filenames and podcast metadata

### ISSUE THREAD

**Issue by ggviana** [devnaestrada/devnaestrada.com.br#5]
It would be great if the podcast had metadata. This should make searching and indexing easier on offline players.
I don't know if this belong here, please tell me if it doesn't.

**Comment by raymonsanches** [comment]
nice suggest @ggviana. What offline player do you use?

**Comment by ggviana** [comment]
Soundcloud [keeps mp3 metadata](https://www.soundcloudcommunity.com/soundcloud/topics/i-uploaded-my-album-to-soundcloud-but-when-you-go-to-download-the-songs-they-open-in-itunes-without-the#reply_15789311) exactly the same way you have uploaded. So I think editing metadata with any ID3 editor should work pretty much anywhere.

**Comment by femontanha** [comment]
Thanks for you advice @ggviana, I'll be more careful with the podcast metadata

**Comment by femontanha** [comment]
Hi @ggviana, I think that I fixed this in our last episode.
http://devnaestrada.com.br/2015/11/20/devnaestrada-28-sou-senior-e-agora.html

Can you see this for me?
If it's correct, I'll apply for another episodes

Thanks

**Comment by ggviana** [comment]
Looks great!
