### ISSUE TITLE
Quick access form with invalid action

### ISSUE THREAD

**Issue by ftonato** [devnaestrada/devnaestrada.com.br#51]
The `<form>` that contains the filter `<select id='filter-form'>` is with an ['action' invalid](https://github.com/devnaestrada/devnaestrada.com.br/blob/77a52aa101f02e11663f939093ce57e17a8ad552/_includes/modules/quick-access.html#L3), it is correct to alter the selected option in the select.

![01](https://cloud.githubusercontent.com/assets/5417662/17226125/4127a0a4-54de-11e6-8486-906186861c07.png)

**Comment by raymonsanches** [comment]
Thank you @CesarDenis for your commit and PR. 
It will be merged on master and deployed very soon! I'll close this issue for now.
