### ISSUE TITLE
Access to episode 64 when click in button "Acessar episódio" do not work

### ISSUE THREAD

**Issue by leandrosimoes** [devnaestrada/devnaestrada.com.br#53]
I'm trying to access the 64 episode by clicking in the "Acessar episódio" button return a 404 page.
![sem titulo](https://cloud.githubusercontent.com/assets/5066378/17247068/c5890922-5566-11e6-9466-8ce2c90c033b.png)

**Comment by raymonsanches** [comment]
Issue confirmed @leandrosimoes.

@CesarDenis PR approved, soon I'll deploy to production. Thank you!
