### ISSUE TITLE
Podcast logo too much generic

### ISSUE THREAD

**Issue by afonsof** [devnaestrada/devnaestrada.com.br#6]
Few months ago when I had subscribed to the podcast in my Android device, I saw the logo and recognised it as the Dev na Estrada one. However some days later I noticed that I had forgotten what that microphone meant to be.

My suggestion is put the website logo instead of using the microphone or insert "Dev na Estrada" under the microphone.

Here's a draft:
![pocket casts](https://cloud.githubusercontent.com/assets/805511/11187358/3d132216-8c6d-11e5-80ee-82ec7a8e7f12.jpg)

**Comment by lnfnunes** [comment]
Maybe the t-shirt "<DNE>" also can be a good option in combination with @afonsof's idea...

**Comment by femontanha** [comment]
![dne-tb](https://cloud.githubusercontent.com/assets/722757/11289301/894c9a02-8f12-11e5-9f07-2e4ea0210bfd.jpg)

Like this? What do you think @lnfnunes @afonsof?

**Comment by afonsof** [comment]
In my opinion it's perfect @femontanha

**Comment by lnfnunes** [comment]
:+1:
