### ISSUE TITLE
Sugestão de participante

### ISSUE THREAD

**Issue by fernandommota** [devnaestrada/devnaestrada.com.br#84]
Fala pessoal,

Gostaria de sugerir a participação do Rodrigo Branas (https://twitter.com/rodrigobranas) para um episódio sobre Node ou mesmo sobre a carreira.

Infelizmente não o conheço, portanto não consigo fazer aquele "meio de campo" citado no dne76, mas o cara é super interessado em ajudar a comunidade, acredito que ele aceitaria de pronto o convite de vocês, exemplo:
- https://www.youtube.com/user/rodrigobranas/playlists  
- https://www.facebook.com/canalrodrigobranas/?fref=ts

Valeu.

**Comment by LedZeck** [comment]
Gosto bastante dos conteúdos do Brana.

Aprendi bastante coisa sobre NodeJs.
Acho bem válida a tentativa de um episódio com ele :)

**Comment by rodinei-jf** [comment]
Seria muito legal um cast com a participação do Rodrigo Branas.

**Comment by gabrielferreiraa** [comment]
Uma boa pessoa sobre NodeJs também poderia ser o @wbruno! Posso falar com ele se quiserem. @raymonsanches permite? kk

**Comment by wbruno** [comment]
opa! =)
seria legal cara.. tô por aqui.

wbrunom@gmail.com

**Comment by rodrigobranas** [comment]
fico a disposição! rodrigo.branas@gmail.com

**Comment by femontanha** [comment]
@fernandommota @gabrielferreiraa Obrigado pelas recomendações! Vamos conversar com eles!

**Comment by fernandommota** [comment]
@femontanha @raymonsanches @rodrigobranas valeu pelo cast galera!!, ficou ótimo como eu esperava =]

Abraços

**Comment by gabrielferreiraa** [comment]
Boa tarde galera, uma ótima recomendação também é o @gustavoguanabara do canal Curso em Vìdeo. Seria interessante abordar uma talk sobre programação no meio acadêmico, ele é professor e instrutor dos cursos do canal dele, caso não conheçam deem uma olhada! Um cast com ele, seria irado!

**Comment by femontanha** [comment]
@gabrielferreiraa, ja tentei contactar ele uma vez e não tive sucesso, você tem acesso a contatos deles? Apresenta o Podcast e veja se ele gostaria de participar.

Valeu

**Comment by gabrielferreiraa** [comment]
Fala @femontanha, beleza? Cara impossível falar com esse Guanabara! Tentei falar com o @suissa pra ver se ele tinha contato fácil, mas não tem também. Vou continuar tentando. Vou deixar aqui mais uma sujestão:

O @dolce, é Front/FullStack em uma afiliada da Rede Globo se não me engano. Tem uns plugins irados de Modal e Alert! Tem certificado Microsoft® Specialist, a talk poderia puxar para esse lado dos certificados, da um papo bom! :) Posso falar com ele se quiserem!

**Comment by femontanha** [comment]
Pessoal, obrigado pelas indicações! Vou fechar esse post!
