### ISSUE TITLE
Pergunta para FAQ

### ISSUE THREAD

**Issue by gabrielferreiraa** [devnaestrada/devnaestrada.com.br#85]
Fala Ramon e Montanha, beleza? Como ser participativo na comunidade dev e ter contato com pessoas influentes na área quando se mora fora dos grandes centros (interior do Paraná no meu caso) onde estão os eventos e meetups?

**Comment by leandrosimoes** [comment]
Fala galera beleza? Primeiramente parabéns pelo cast, está cada dia melhor. 

Gostaria muito de gravar um podcast meu sobre programação, porém com uma pegada mais técnica. Gostaria de saber quais equipamentos vocês indicariam, marca de microfone, se é de lapela, se é direcional, se usam placa de som para gravação, qual programa usam para a edição. Bom, uma geral nos equipamentos que vcs utilizam. Valeu galera!

**Comment by brunoqcx** [comment]
Olá Pessoal Ótimo Podcast, anima muito minhas viagens.
Gostaria de uma dica de vcs pra quem está começando na área desenvolvimento JS:
Vale mais a pena investir tempo num framework e sair produzindo portfólio e ir aprofundando no JS aos poucos ou o ideal é conhecer BEM a linguagem antes de pegar algo do tipo ? (os caras do podcast codingBlocks fizeram uma pesquisa por lá e ficou bem dividido, queria saber também a opinião de vocês)

**Comment by coveiro88** [comment]
Meu nome é Jader, tenho 28 anos e curso sistemas de informação.
Tenho muita dificuldade em ter boa lógica de programação. Estou estudando linguagem C na faculdade, porém já reprovei 3x em programação I. Sei toda a sintaxe, mas tenho problemas quando sou submetido as provas, que no caso são difíceis em relação a essa lógica. 
Teriam alguma dica para que eu possa melhorar essa deficiência?

Grande abraço, sou muito fã de vocês!

**Comment by tiagofaustino** [comment]
Fala povo!!
Como sair da pontuação 1 no StackOverflow?? Abraços!!

**Comment by diegoaad** [comment]
Fala Ramon e Montanha, pergunta relacionada a podcasts de forma geral. Uma duvida que sempre tive foi com relação ao feedback/stats que vocês tem em relação ao numero de downloads, numero de pessoas que escutaram um episódio especifico. Acredito que pelo itunes ou soundcloud seja mais facil pegar esses numeros, mas e no caso de pessoas que ouvem através de apps agregadores de podcasts (eg. no meu caso uso o podcast addicted)? Vocês tem como ver esses numeros e saber qtas pessoas baixaram ou ouviram algum episodio mesmo através de outros apps?

**Comment by simaodeveloper** [comment]
Fala galera, seguinte vocês acham que o JSON-LD chegou para matar o Microdata, pois o dois foram construídos em cima do Schema, explica para nós para que servem e quais suas diferenças, valeu pessoal o/

**Comment by leandrosimoes** [comment]
Fala galera beleza? O @femontanha disse que trabalhou (ou ainda está trabalhando) em um projeto react-native. Gostaria de saber quais são as impressões que ele teve sobre o framework, se ele recomenda este framework e se ele tem alguns sites, cursos, apostilas e etc para indicar pra quem está começando (no caso eu). Valeu, abraço!

**Comment by femontanha** [comment]
Obrigado pelas perguntas, vou fechar esse tópico por esse ano :)
