### ISSUE TITLE
StackOverflow

### ISSUE THREAD

**Issue by tiagofaustino** [devnaestrada/devnaestrada.com.br#86]
Fala povo!!
Como sair da pontuação 1 no StackOverflow?? Abraços!!

**Comment by leandrosimoes** [comment]
@tiagofaustino Creio eu que as perguntas para o próximo FAQ devem ser postadas [NESTA ISSUE](https://github.com/devnaestrada/devnaestrada.com.br/issues/85) para ficarem centralizadas em um único local blz? Abraço!

**Comment by tiagofaustino** [comment]
Vlw!
