### ISSUE TITLE
Lógica de programação

### ISSUE THREAD

**Issue by coveiro88** [devnaestrada/devnaestrada.com.br#87]
Meu nome é Jader, tenho 28 anos e curso sistemas de informação.
Tenho muita dificuldade em ter boa lógica de programação.  Estou estudando linguagem C na faculdade, porém já reprovei 3x em programação I. Sei toda a sintaxe, mas tenho problemas quando sou submetido as provas, que no caso são difíceis em relação a essa lógica. 
Teriam alguma dica para que eu possa melhorar essa deficiência?

Grande abraço, sou muito fã de vocês!

**Comment by leandrosimoes** [comment]
@coveiro88 Creio eu que as perguntas para o próximo FAQ devem ser postadas [NESTA ISSUE](https://github.com/devnaestrada/devnaestrada.com.br/issues/85) para ficarem centralizadas em um único local blz? Abraço!

**Comment by coveiro88** [comment]
Valeu mesmo cara!! vou postar lá.

**Comment by leandrosimoes** [comment]
Por nada @coveiro88 só da um "Close" aqui nessa issue assim que possível fazendo um favor.

**Comment by raymonsanches** [comment]
;)
