### ISSUE TITLE
Alguns podcasts indisponíveis para agregadores

### ISSUE THREAD

**Issue by idlua** [devnaestrada/devnaestrada.com.br#91]
Alguns podcasts do DNE estão indisponíveis de serem acessados por agregadores. Seja pra download ou pra transmissão online. Testei em 3 apps diferentes pra Android ([Pocket Casts][podcast1], [CastBox][podcast2] e [Radio Addict][podcast3]).

Os que entram nesse loop infinito de carregamento são os DNE 02, 55, 56, 60, 73 e 78. Tem ideia do que pode ser? Não sei se alguém teve o mesmo problema e já reportou.

No mais, valeu por criarem o DNE! Vocês são fodas!!

[podcast1]: https://play.google.com/store/apps/details?id=au.com.shiftyjelly.pocketcasts
[podcast2]: https://play.google.com/store/apps/details?id=com.podcast.podcasts
[podcast3]: https://play.google.com/store/apps/details?id=com.bambuna.podcastaddict

**Comment by femontanha** [comment]
Fala @idlua ninguém nunca reportou esse problema!
Eu uso o PocketCasts e está funcionando normalmente :(
Não tenho idéia do que pode ser, o feed está ok.
Tenta acessar pelo APP do Soundcloud, mas deveria estar funcionando sim cara.

**Comment by idlua** [comment]
Eu vi alguns reports no site do app com esse problema, mas nem eles sabem o que acontece. Estranho.

Valeu Montanha! Vou continuar ouvindo pelo app do SoundClound esses aí
